
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `appointment` DISABLE KEYS */;
/*!40000 ALTER TABLE `appointment` ENABLE KEYS */;

/*!40000 ALTER TABLE `chatbox` DISABLE KEYS */;
/*!40000 ALTER TABLE `chatbox` ENABLE KEYS */;

/*!40000 ALTER TABLE `chatboxRole` DISABLE KEYS */;
/*!40000 ALTER TABLE `chatboxRole` ENABLE KEYS */;

/*!40000 ALTER TABLE `chatboxUser` DISABLE KEYS */;
/*!40000 ALTER TABLE `chatboxUser` ENABLE KEYS */;

/*!40000 ALTER TABLE `expert_available_slots` DISABLE KEYS */;
/*!40000 ALTER TABLE `expert_available_slots` ENABLE KEYS */;

/*!40000 ALTER TABLE `expert_payout_methods` DISABLE KEYS */;
/*!40000 ALTER TABLE `expert_payout_methods` ENABLE KEYS */;

/*!40000 ALTER TABLE `expert_profile` DISABLE KEYS */;
/*!40000 ALTER TABLE `expert_profile` ENABLE KEYS */;

/*!40000 ALTER TABLE `invoice` DISABLE KEYS */;
/*!40000 ALTER TABLE `invoice` ENABLE KEYS */;

/*!40000 ALTER TABLE `invoice_item` DISABLE KEYS */;
/*!40000 ALTER TABLE `invoice_item` ENABLE KEYS */;

/*!40000 ALTER TABLE `message` DISABLE KEYS */;
/*!40000 ALTER TABLE `message` ENABLE KEYS */;

/*!40000 ALTER TABLE `payout_requests` DISABLE KEYS */;
/*!40000 ALTER TABLE `payout_requests` ENABLE KEYS */;

/*!40000 ALTER TABLE `report` DISABLE KEYS */;
/*!40000 ALTER TABLE `report` ENABLE KEYS */;

/*!40000 ALTER TABLE `reviews` DISABLE KEYS */;
/*!40000 ALTER TABLE `reviews` ENABLE KEYS */;

/*!40000 ALTER TABLE `transaction` DISABLE KEYS */;
/*!40000 ALTER TABLE `transaction` ENABLE KEYS */;

/*!40000 ALTER TABLE `user` DISABLE KEYS */;
REPLACE INTO `user` VALUES (1,NULL,'admin',NULL,NULL,NULL,'admin@ibody.com','Administrator');
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

/*!40000 ALTER TABLE `userAuthPassword` DISABLE KEYS */;
/*!40000 ALTER TABLE `userAuthPassword` ENABLE KEYS */;

/*!40000 ALTER TABLE `userGroup` DISABLE KEYS */;
REPLACE INTO `userGroup` VALUES (1,NULL,'baseuser');
/*!40000 ALTER TABLE `userGroup` ENABLE KEYS */;

/*!40000 ALTER TABLE `userGroup_permission` DISABLE KEYS */;
/*!40000 ALTER TABLE `userGroup_permission` ENABLE KEYS */;

/*!40000 ALTER TABLE `userPermission` DISABLE KEYS */;
/*!40000 ALTER TABLE `userPermission` ENABLE KEYS */;

/*!40000 ALTER TABLE `user_group` DISABLE KEYS */;
/*!40000 ALTER TABLE `user_group` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

